name: hellow-world
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Displays hello world message
        run: echo "Hello World!"
        
      - name: Another Task
        run: echo "Another Task"  
      
      
