name: hello world

on:
  workflow_dispatch:  
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: "*/5 * * * *" # executes every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Displays hello world message
        run: echo "Hello World!"
        
      - name: Another Task
        run: echo "Another Task"  
