name: hello world

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    paths:
      - 'code/**'
      - '.github/workflows/hello-world.yml'
    branches:
      - main
  # schedule:
  #   - cron: "*/5 * * * *" # executes every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Displays hello world message
        run: echo "Hello World!"
        
      - name: Another Task
        run: echo "Another Task"  
      - name: Checkout
        uses: actions/checkout@v4.2.2 
      - name: List the files of the repo
        run: |
            echo "The repository ${{ github.repository }} contains the following files:"
            tree
